name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda create --prefix ./.env
        conda activate ./.env
        conda install mamba -c conda-forge -y
        mamba env update --file environment.yml
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Build with conda
#      uses: cascode-labs/build-conda-action@v0.1.4
#      with:
#        recipe_path: meta.yaml
#        conda_build_env_filepath: ./.env
#        conda_build_env_name: action_default
#        base_env_prefix: $CONDA/bin/conda
#        package_artifact_name: rat
#        # Options to be passed to conda-build
#        build_options: -c conda-forge -c defaults
    - name: Publish Conda
      uses: fcakyon/conda-publish-action@v1.3
      with:
        subdir: .
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: noarch
