name: test

on: [push]

jobs:
  test:
    name: Install package and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup environment with miniconda/mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge, defaults
          channel-priority: true
          activate-environment: rat
          environment-file: dev-environment.yml
      - name: Install RAT in developer mode
        run: |
          mamba install conda-build
          conda develop src/
      - name: Test RAT
        shell: bash -l {0}
        run: |
          mkdir ~/rat_test
          python src/rat/cli/rat_cli.py init -d ~/rat_test
          python src/rat/cli/rat_cli.py test -d ~/rat_test
